### ISSUE TITLE
empty files generated during preprocess

### ISSUE THREAD

**Issue by jzhoubu** [dojoteef/synst#2]
Hi, I encountered the same issue as #1. Specifically, during the preprocessing,  `*.parse` are empty files. 
However, I fail to solve this issue with `jq` installed and setting `LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8`.

Is there any other suggestion or possible solution here?

**Comment by dojoteef** [comment]
Hi @sysu-zjw

Since you have `jq` installed and habe correctly set `LC_ALL`, your error could be due to the java based parser, CoreNLP.

Can you verify that you can run the parser on it’s own? You can see scripts/parse.sh to see how it is currently called.

**Comment by jzhoubu** [comment]
Hi @dojoteef I figured out that I should set `LC_ALL= ` instead of `LC_ALL=en_US.UTF-8`. Now I am able to generate non-empty results by executing:
```
LANG=en_US.UTF-8 LC_ALL= CLASSPATH=./stanford-corenlp-full-2018-10-05/* python main.py \
  --dataset wmt_en_de_parsed --span 6 -d raw/wmt -p preprocessed/wmt -v pass
```
I will close the issue. Thank you for the quick reply :D
