### ISSUE TITLE
Questions about running codes on iwslt dataset

### ISSUE THREAD

**Issue by huaishengzhu** [dojoteef/synst#5]
I have preprocessed iwslt dataset successfully by running `CLASSPATH=stanford-corenlp-full-2018-10-05/* LC_ALL=en_US.UTF-8 LANG= python3 main.py   --dataset iwslt_en_de_parsed --span 6 -d raw/iwslt -p preprocessed/iwslt -v pass`, but when I start to train this model by `CLASSPATH=stanford-corenlp-full-2018-10-05/* LANG=en_US.UTF-8 LC_ALL= python3 main.py -b 3175 --dataset iwslt_en_de_parsed --span 6 --model parse_transformer -d raw/iwslt -p preprocessed/iwslt -v train --checkpoint-interval 1200  --label-smoothing 0
`, I got the following error:
`Traceback (most recent call last):`
  `File "main.py", line 93, in <module>  `
    `main()  `
 `File "main.py", line 89, in main  `
    `action(epoch, args.experiment, args.verbose)`  
  `File "/home/qul/NLP/New Research/tmp/synst/actions/train.py", line 274, in __call__`  
    `self.train_epoch(epoch, experiment, verbose)`  
  `File "/home/qul/NLP/New Research/tmp/synst/actions/train.py", line 132, in train_epoch`  
    `for i, batch in enumerate(batches, 1):`  
  `File "/home/qul/Python3.6/Python-3.6.6/lib/python3.6/site-packages/tqdm/_tqdm.py", line 937, in __iter__ ` 
    `for obj in iterable: ` 
  `File "/home/qul/Python3.6/Python-3.6.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__`
    `return self._process_next_batch(batch)`  
 ` File "/home/qul/Python3.6/Python-3.6.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch`
    `raise batch.exc_type(batch.exc_msg)`  
`AssertionError: Traceback (most recent call last):`  
  `File "/home/qul/Python3.6/Python-3.6.6/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop`
    `samples = collate_fn([dataset[i] for i in batch_indices])`  
  `File "/home/qul/Python3.6/Python-3.6.6/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>`
    `samples = collate_fn([dataset[i] for i in batch_indices]) ` 
  `File "/home/qul/NLP/New Research/tmp/synst/data/text.py", line 43, in __getitem__
    (i, self.tensorize(i)) for i in index ` 
  `File "/home/qul/NLP/New Research/tmp/synst/data/text.py", line 43, in <genexpr>
    (i, self.tensorize(i)) for i in index`  
  `File "/home/qul/NLP/New Research/tmp/synst/data/annotated.py", line 253, in tensorize
    datum['target'], target_annotation, target_spans`  
  `File "/home/qul/NLP/New Research/tmp/synst/data/annotated.py", line 227, in annotated_sequence`
    `assert not original_target`  
`AssertionError`
So, can you help me to solve this error or give me an example to run this code on iwslt dataset.

**Comment by dojoteef** [comment]
You seem to be getting the same error as was reported in issue #1. Specifically, the problem the individual was having was that their [preprocessed files with the `.parse` extension were empty](https://github.com/dojoteef/synst/issues/1#issuecomment-518004156). Can you please verify if your parse files have valid data in them? If not, can you try the fixes described in that issue?

**Comment by huaishengzhu** [comment]
Thank you for your reply, my `.parse` files were not empty. It seemed that I had preprocessed data successfully. Is there any mistake on my command for iwslt dataset by `python3 main.py -b 3175 --dataset iwslt_en_de_parsed --span 6 --model parse_transformer -d raw/iwslt -p preprocessed/iwslt -v train --checkpoint-interval 1200 --label-smoothing 0` to train the model?

**Comment by dojoteef** [comment]
Here are the [MD5 hashes](https://github.com/dojoteef/synst/files/3688526/iwslt_md5.txt) of my `.parse` files for IWSLT. Can you compare and let me know if they are the same?

**Comment by huaishengzhu** [comment]
It seemed that my training files are different from you, here is my [MD5 hashes](https://github.com/dojoteef/synst/files/3688600/iwslt.txt)

_

**Comment by dojoteef** [comment]
Hmm... I'm not sure what's wrong with your training files, but let's see if you can train on the validation set without error. Can you try running:

```
python3 main.py -b 3175 --dataset iwslt_en_de_parsed --span 6 --model parse_transformer -d raw/iwslt -p preprocessed/iwslt --split dev -v train --checkpoint-interval 1200 --label-smoothing 0
```

**Comment by huaishengzhu** [comment]
It seemed that there was something wrong on my training files, I can run this command successfully.

**Comment by dojoteef** [comment]
Can you try figuring out what went wrong in your training file by debugging a bit? Look at the difference between the contents of the preprocessed dev files versus the training files. Then possibly put a break point in the code and step through it a bit.

Another simple check is to verify that `train.en` has the same number of lines as `train.tok.en.parse`.

Let me know how that goes.

**Comment by huaishengzhu** [comment]
The lines of `train.en` are fewer than those of `train.tok.en.parse`

**Comment by dojoteef** [comment]
My guess is that it has something to do with character encodings, but I'm not sure exactly what the issue is. If there are a different number of lines, you can try to do a binary search between both files to find where the first difference is and see what went wrong. Likely some character is being treated as a newline.

My only guess is that this is happening somewhere [here](https://github.com/dojoteef/synst/blob/master/scripts/parse.sh#L40-L42). I would try doing those commands separately and writing each out to a file, then analyzing each file to see which command is introducing the bug.

**Comment by huaishengzhu** [comment]
I guesss whether this problem is caused by the vesion of `spacy`, can you tell me your version of `spacy`?

**Comment by dojoteef** [comment]
`2.0.12`

**Comment by huaishengzhu** [comment]
It seemed that I had solved this problem by running `parse.sh` immadiately to solve this problem, I don't know what is the problem when I run python to preprocess this data.

**Comment by huaishengzhu** [comment]
Anyway, can you give me an example parameter for running this code on iwslt or just the same as wmt's?

**Comment by huaishengzhu** [comment]
I'm sorry to disturb you again that I have met anothor problems during training when I kept my MD5 hashes the same as you. I met the following error during the training process about finishing 47% training by running `python3 main.py -b 3175 --dataset iwslt_en_de_parsed --span 6 --model parse_transformer -d raw/iwslt -p preprocessed/iwslt -v train --checkpoint-interval 1200 --label-smoothing 0`:
```sh
File "main.py", line 93, in <module>
    main()
  File "main.py", line 89, in main
    action(epoch, args.experiment, args.verbose)
  File "/home/qul/NLP/New Research/tmp/synst/actions/train.py", line 274, in __call__
    self.train_epoch(epoch, experiment, verbose)
  File "/home/qul/NLP/New Research/tmp/synst/actions/train.py", line 132, in train_epoch
    for i, batch in enumerate(batches, 1):
  File "/home/qul/Python3.6/Python-3.6.6/lib/python3.6/site-packages/tqdm/_tqdm.py", line 937, in __iter__
    for obj in iterable:
  File "/home/qul/Python3.6/Python-3.6.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/qul/Python3.6/Python-3.6.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 606, in _process_next_batch
    raise Exception("KeyError:" + batch.exc_msg)
Exception: KeyError:Traceback (most recent call last):
  File "/home/qul/Python3.6/Python-3.6.6/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/qul/Python3.6/Python-3.6.6/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/qul/NLP/New Research/tmp/synst/data/text.py", line 43, in __getitem__
    (i, self.tensorize(i)) for i in index
  File "/home/qul/NLP/New Research/tmp/synst/data/text.py", line 43, in <genexpr>
    (i, self.tensorize(i)) for i in index
  File "/home/qul/NLP/New Research/tmp/synst/data/annotated.py", line 248, in tensorize
    if self.annotation is TextAnnotation.CONSTITUENCY_PARSE
  File "/home/qul/NLP/New Research/tmp/synst/data/annotated.py", line 247, in <listcomp>
    [self.token2id[annotation] for annotation in target_annotation]
KeyError: '<ISU6>'
```

**Comment by dojoteef** [comment]
Sorry I wasn't able to respond sooner, I've been a bit busy. I just provided hyperparameter info in #3. See [here](https://github.com/dojoteef/synst/issues/3#issuecomment-540246276).
