### ISSUE TITLE
预处理出现问题，如何正常处理？

### ISSUE THREAD

**Issue by Shajiu** [dojoteef/synst#7]
作者您好！请问您的源码我怎么运行失败呢？尤其是预处理问题，存在很大的问题，这是怎么回事儿？

**Comment by SimengSun** [comment]
你好，请问可以具体说一下是预处理哪部分的问题吗？

**Comment by Shajiu** [comment]
我环境都搭建好了，您方便给我预处理时各个文件夹下的每个文件的样例么？我想利用我自己的数据进行实验。非常感谢您！

**Comment by SimengSun** [comment]
你好，如果可以提供报错信息的话可以更加方便发现哪里出现了问题。

预处理后比较重要的几个文件有:
- `bpe.32000`: BPE codes with 32000 merge operations, 这个文件可以自己提供也可以通过预处理代码得到，自己提供的话可以使用[subword-nmt](https://github.com/rsennrich/subword-nmt)
- `vocab.bpe.32000`：这个是shared subword vocab
- `{train, valid, test}.tok.bpe.32000.{lang}`：如果是en-de数据集的话lang替代为en或de。这个是tokenized 并且已经切分为subword的parallel数据集。该条及以上对应预处理代码在[这里](https://github.com/dojoteef/synst/blob/a1842682cf757e8a501cd9cee16f20e1a14158f1/data/annotated.py#L288)
- `{train, valid, test}.tok.bpe.32000.bin`:  这个是parallel dataset被预处理后的在训练和测试过程中使用的.bin文件，详细代码看[这里](https://github.com/dojoteef/synst/blob/a1842682cf757e8a501cd9cee16f20e1a14158f1/data/annotated.py#L470)

**Comment by Shajiu** [comment]
您好！我在文件夹“wmt_en_de_parsed”下放了：test.tok.bpe.32000.en 、train.tok.bpe.32000.en  、valid.tok.bpe.32000.en、  vocab.bpe.32000（英文词汇后面接着放了中文词汇、一行为一个词汇）、test.tok.bpe.32000.zh、  train.tok.bpe.32000.zh  、valid.tok.bpe.32000.zh
然后运行：python main.py --dataset ./wmt_en_de_parsed/ --span 6 -d raw/wmt/ -p ./preprocessed/wmt/ -v pass      
 raw/wmt/和./preprocessed/wmt/为空文件夹，出现如下错误：
main.py: error: argument -D/--dataset: invalid choice: './wmt_en_de_parsed/' (choose from 'wmt_en_de', 'wmt_de_en', 'wmt_en_de_parsed', 'wmt_de_en_parsed', 'wmt_en_de_spans', 'wmt_de_en_spans', 'wmt_en_fr', 'wmt_fr_en', 'wmt_en_fr_parsed', 'wmt_fr_en_parsed', 'wmt_en_fr_spans', 'wmt_fr_en_spans', 'wmt_full_en_fr', 'wmt_full_fr_en', 'wmt_full_en_fr_parsed', 'wmt_full_fr_en_parsed', 'wmt_full_en_fr_spans', 'wmt_full_fr_en_spans', 'iwslt_en_de', 'iwslt_de_en', 'iwslt_en_de_parsed', 'iwslt_de_en_parsed', 'iwslt_en_de_spans', 'iwslt_de_en_spans')

**Comment by SimengSun** [comment]
你好，请试一下`python main.py --dataset wmt_en_de_parsed --span 6 -d raw/wmt/ -p ./preprocessed/wmt/ -v pass` 然后把所有以zh为结尾的文件改为de，因为wmt_en_de_parsed支持的target language是德语。

**Comment by Shajiu** [comment]
您好!我按照您的说法作了、可还是出现以上所出现的问题，方便加您微信具体截图给您么？跪求万分感谢

**Comment by Shajiu** [comment]
作者您好！我想重数据下载、预处理开始搭建，我在synst-master/下运行python data/annotated.py时出现：
Traceback (most recent call last):
  File "data/annotated.py", line 19, in <module>
    import metrics
  File "/home2/sj/translation/synst-master/metrics/__init__.py", line 14, in <module>
    import utils
  File "/home2/sj/translation/synst-master/data/utils.py", line 14, in <module>
    from data.sampler import SequenceLengthSampler
  File "/home2/sj/translation/synst-master/data/__init__.py", line 6, in <module>
    from data.annotated import TextAnnotation
  File "/home2/sj/translation/synst-master/data/annotated.py", line 20, in <module>
    from data import preprocess
  File "/home2/sj/translation/synst-master/data/preprocess.py", line 24, in <module>
    import utils.file as file_utils
ModuleNotFoundError: No module named 'utils.file'; 'utils' is not a package
可是在当前环境下进入python环境，然后以上出现错误的导入包一个个导入时没有任何问题呢？这是怎么回事儿啊？万分感谢作者

**Comment by Shajiu** [comment]
作者您好！我多次出现：ModuleNotFoundError: No module named 'utils.file'; 'utils' is not a package
这个“utils”是python内置的函数调用还是您在/data/下所写的“utils.py”文件呢？是不是文件名称冲突的问题呢？

**Comment by SimengSun** [comment]
你好，如果想要预处理数据集，你需要这个指令：
`CLASSPATH=stanford-corenlp-full-2018-10-05/* python main.py \
  --dataset wmt_en_de_parsed --span 6 -d raw/wmt -p preprocessed/wmt -v pass`

这个指令针对wmt中英语与德语的数据集，如果你当前文件夹没有这个数据集，程序会自动下载数据，对应代码在[这里](https://github.com/dojoteef/synst/blob/a1842682cf757e8a501cd9cee16f20e1a14158f1/data/wmt.py#L10)。如果想要处理中文数据集，你可以在这个文件里加入一个新的类处理中文数据集的下载和切分。

**Comment by Shajiu** [comment]
还是出现问题啊！

**Comment by Shajiu** [comment]
出现这样的错误，您好！方便加微信么？谢谢您啦
main.py: error: invalid choice: ' train' (choose from 'train', 'evaluate', 'translate', 'pass')

**Comment by Shajiu** [comment]
您好！请问方便加微信联系么？
