### ISSUE TITLE
Getting error while executing in google colab

### ISSUE THREAD

**Issue by kr-sundaram** [dojoteef/synst#8]
Thank you for making this repo public!!

I am new to this Neural Machine Translation field and wanna reproduce your results in Google Colab. Below steps i followed.

1. Installed the python packages as given in requirements.txt files.

2. Downloaded all the files and kept them in folder as written in the readme file.
a. stanford-corenlp-full-2018-10-05.zip
b. stanford-srparser-2014-10-23-models.jar
c. stanford-french-corenlp-2018-10-05-models.jar
d. stanford-german-corenlp-2018-10-05-models.jar

3. set the java classpath using below code:
import os
javapath = "/content/drive/My Drive/SynST/stanford-corenlp-full/*"
os.environ['CLASSPATH'] = javapath

4. Ran the python script for Preprocessing:

!python main.py \
  --dataset wmt_en_de_parsed --span 6 -d raw/wmt -p preprocessed/wmt -v pass

Got below error:

fatal: not a git repository (or any parent up to mount point /content)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Traceback (most recent call last):
  File "/content/drive/My Drive/SynST/utils/__init__.py", line 92, in get_version_string
    version = check_output(['git', 'describe', '--always', '--dirty'], encoding='utf-8')
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'describe', '--always', '--dirty']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 93, in <module>
    main()
  File "main.py", line 31, in main
    args = parse_args(argv)
  File "/content/drive/My Drive/SynST/args.py", line 636, in parse_args
    args.version = get_version_string()
  File "/content/drive/My Drive/SynST/utils/__init__.py", line 94, in get_version_string
    raise RuntimeError('Call to "git describe" failed!')
RuntimeError: Call to "git describe" failed!

Could you please help me reproducing your results.

**Comment by dojoteef** [comment]
This error is stating that you are running the script outside of the git repository (the code tries to automatically determine the git revision of the code begin run). If you cannot run the code directly from the directory of the git repository, you can simply replace the call to `get_version_string()` with the empty string:

```
args.version = ""
```
